---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release-cert-manager.yaml
  - release-promstack.yaml
  - release-stackgres-operator.yaml
  - release-haproxy-ingress.yaml
  - release-traefik.yaml
